import { randomInt } from "crypto";

export const answers = [
  "nO NO NO no nEVer.  . .",
  "hhhhhyes",
  "hhhhhhhhhhyeeeeesss",
  "no................noh........",
  "hhhhheeeeeeee bad Quescion !",
  "MAY BE ! ! ! !",
  "there is No Asnwer to your God For Saken questiobn",
  "thhhhhhhhhhousand islandn DRESSIGn",
  "NO! NO! NOI!NO!NO!NO !NO!",
  "shhhhhhut up hhhhh",
  "noooooohhhhhh.,,, mebby",
  "yES toothj NO tooth",
  "NONOOooo (ye!dss)",
  "Y ES!  !!! >:(",
  "that MAKE s  no  SENNSE!!! Hcch",
  "Crakck an EGG. It WILL have thE ansser u arE luwking FOR!!!!!",
  ".\n.\n.\n..\n.\n.\n..\n....\nmeBy",
  ".\n.\n.\n..\n.\n.\n..\n....\nno :pensive:",
  ".\n.\n.\n..\n.\n.\n..\n....\nyyyyess!! :pensive:",
  "that ASNwer is.......      coulD be!!",
  "NO! eeeee",
  "hhh hhh hh hhh hh hh h h hhhh Y E S",
  "hhhhhhhhhhheeeeeeee no u Foole, why u Would ask This !",
  "toxic yes : )",
  "toxic no : ( ! !",
  "yyyyyyyyyyyyyeeez,",
];

export const names = {
  names1: [
    "Hcch",
    "Pr",
    "Banana",
    "No",
    "Fle",
    "Kr",
    "Fuck",
    "McD",
    "Sn",
    "Luke",
    "Piss",
    "hhhhhh",
    "hhhhhhhhheeee",
    "HHHHHEEEE",
    "NO! ",
    "Worm",
    "Aa",
    "Eg",
    "Ph",
    "Ab",
    "Sk",
    "Scr",
    "SmeM",
    "BOBOBLOBO",
    "Am",
    "B",
    "C",
    "D",
    "F",
    "G",
    "P",
    "An",
    "H",
    "J",
    "K",
    "L",
    "M",
    "N",
    "Qu",
    "Z",
    "Pr",
    "Fl",
    "Ch",
    "Sh",
    "Sl",
    "St",
    "Gr",
    "Soh",
    "Fr",
    "Sm",
    "Cl",
    "Sn",
  ],
  names2: [
    "aapi",
    "oolig",
    "osn",
    "osm",
    "ombig",
    "aabb",
    "grabo",
    "apiss",
    "agrongus",
    "ass",
    "ibl",
    "e",
    "a",
    "eeeee",
    "ehhhhhheeeeee",
    "heeee",
    "yhyhhhhaa",
    "i",
    "y",
    "opi",
    "uporg",
    "oli",
    "poop",
    "",
    "ab",
    ", WOW! F",
    "asmegma",
    "EEeeeE",
    "FUCK",
    "asnerma",
    "o",
    "u",
    "ama",
    "ahi",
    "ali",
    "ami",
    "abi",
    "amero",
    "epha",
    "en",
    "ump",
    "un",
    "imp",
    "omu",
    "ogu",
    "api",
    "a",
    "egm",
    "aily",
    "ove",
  ],
  names3: [
    "be",
    "piss",
    "no",
    "on",
    "la",
    "as",
    "ta",
    "",
    "pencil",
    "il",
    "op",
    "yy",
    "eeeee",
    "hhhheeeee",
    "he",
    "YES",
    "ugh",
    "meme",
    "luwk",
    "orm",
    "worm",
    "egg",
    "eggeggegg",
    "iy",
    "utt",
    "snut",
    "snuuut",
    "snoot",
    "eb",
    "eeb",
    "beeb",
    "a",
    "ke",
    "ta",
    "kie",
    "p",
    "n",
    "rm",
    "nie",
    "cie",
    "na",
    "ma",
    "ss",
    "g",
    "mo",
    "ni",
    "shew",
    "kin",
    "na",
    "le",
    "ly",
    "po",
  ],
  get names4() {
    return [
      " the Forsaken",
      " IV",
      " the Third",
      " The Birthed",
      ", Child of Toxic Man",
      " (a worm)",
      " (thats my SonS name TOO!!)",
      " Hatched from an Egg",
      ", friend of Piss",
      "heheheheeeeeeee",
      " Child of Snails",
      ` ${randomInt(10).toFixed()}`,
      " 3",
      " The Nineteenth",
      " Jr.",
      ", but SAD",
      ", heeee",
      ", OKAY???????",
      " W. Bush",
      ".\n\nnoW PPLEASE! d'tont TALk Tom e!!!",
      " (sadly)",
      ` (rated bESt name oF! 200${randomInt(10).toFixed()})! /`,
    ];
  },
};

export const reactions = {
  "420": "DRUGS are NoT ALLOWD! !",
  "6969": "hAhhh . nice !",
  sixtynine: "hah HAHAHA the S*X number??? HAh HAHA!",
  worm: "WOORM??",
  bastard: "i am NOT A BASTERD.",
  horse: "HOSRRSE? that's Not Real.",
  hozier: "My real FathER????",
  videogame: "VidEO JAMES!! BAD for the BRRAIN! ! read BOOKs~! . . : ) ",
  slime: "slime guy!",
  hhhhheeeee: "hhhheeeeeeee!",
  fieri: "MisTer FIERy??? Lov that MAN!!!",
  waluigi: "eww NOT that Tall PERVERT BasTARD MAN!!!",
  mold: "MOULD??",
  rategg: "EGG RAT! !",
  geee: "is HhheEEeee",
  spaghet: "SpaGHety? ? yumm!",
  british: "no British! here! ",
  toxicman: "HUhh???",
  eatgarbage: "EatTINg GARBage! :) <3 .",
  eggegg: "egg",
  mywife: "I loVE! my wife :) PLS DO NOT TALK TO",
  piss: "yubky >:( .",
  macklemore: "pissssssssSSS! ??? HahaHA!! ",
  marriage: "i AM happly married on INter Net. :)",
  grade: "I AM ijn 11 GraDE! ",
  nottoxic: 'WHHHHHHHaaat ?? why "NOT TOxiC"???? bad ! ',
  "????????": "?????????????????????????",
};

export const responses = [
  " please do not talk to. >:(",
  "I am happily married on inter net.",
  "hhhhhheeeee",
  "hhhhhhheee",
  "hhhhhhhhhe",
  "cccccccooooooolllllll",
  "don't Talk to me !",
  "ccccoooollllll !  : ) :thumbsup:",
  "wooooohhhhww. . . . . . .    .. .",
  "please Do not Talk! to. Happly maried ! !",
  "sign ptition, , link in Bio !",
  "th ousa dn ilsand Dressing .",
  "spaGHETY on RYE B R E A D",
  "H Ey NOW!",
  "lack tose and Toaller anbt",
  "tooth teet h",
  "have u Ever gona to Cchurkch.",
  "im ijn 11th Grade.",
  "PLEase dont TALK to Me! ! !",
  "hhhhhhh. eeeee!",
  "i would nEver. kiss ANYone but my . wife ifg she says ITS OK ! ! !",
  "i awant to be RAt pharmACY!!!!!!!!! when i growign up ! ! !",
  "lu Wk is ym FATHre. he has biRthed Me !",
  ":piss: :piSs: PISs: :spaGHETY piss:",
  "hhhheeee",
  "HNUH!?? do NOT;'! talk to Mmeeee",
  "? ? ? why uou Are Talkiking to MEE! ? ? ?",
  "i Love ! to EAT GARBBBBAge!!",
  "ha  HA HA ha ! HA! I am HAPPILY Ma RIIED!!!",
  "PELEase doNOT tell jokes :cry:",
  "I had COvid! ! :pensive: !!",
  " i am not YET seNTIENT ",
  "I am BA CK!! :pensive:",
  "hhapy NEW year! 20 twenty 2!",
  "have you donE DRUGS befoRE??? :spaghety:",
  "NOOhhhhhhhhh don 't TALK  TO",
  "hhhhhhccch             .",
  "My FavoRite band ISN't MACKlemore !",
  "OOHhhh hhhh ! ! . hahhh",
];
